dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - lsb_release -a
  - sudo apt-get update
  - sudo mkdir /home/runs
install:
  - sudo apt-get install default-jdk
script:
  - gcc --version
  - java -version
  - ls /home/runs
