dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-get update
  - sudo apt-get install dchroot debootstrap
  - sudo mkdir /JAIL/
  - sudo chmod 777 /etc/schroot/schroot.conf
  - sudo echo "[xenial]" > /etc/schroot/schroot.conf
  - sudo echo "description=Ubuntu Xenial Xerus" > /etc/schroot/schroot.conf
  - sudo echo "location=/JAIL" > /etc/schroot/schroot.conf
  - sudo echo "priority=3" > /etc/schroot/schroot.conf
  - sudo echo "users=ahmed-dinar" > /etc/schroot/schroot.conf
  - sudo echo "groups=sbuild" > /etc/schroot/schroot.conf
  - sudo echo "root-groups=root" > /etc/schroot/schroot.conf
  - sudo debootstrap --variant=buildd --arch amd64 xenial /JAIL/ http://mirror.math.princeton.edu/pub/ubuntu/
  - sudo mount proc /JAIL/proc -t proc
  - sudo chroot /JAIL/
