dist: xenial
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - sudo chmod +x install-chroot.sh
  - sudo ./install-chroot.sh
install:
  - sudo chroot /JAIL yes Yes | ./setup-chroot.sh
script:
  - sudo echo "done!"
