dist: xenial
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-get update
  - sudo apt-get install dchroot debootstrap
  - sudo mkdir /JAIL/
  - sudo chmod 777 /etc/schroot/schroot.conf
  - sudo echo "[xenial]" > /etc/schroot/schroot.conf
  - sudo echo "description=Ubuntu Xenial Xerus" > /etc/schroot/schroot.conf
  - sudo echo "location=/JAIL" > /etc/schroot/schroot.conf
  - sudo echo "priority=3" > /etc/schroot/schroot.conf
  - sudo echo "users=ahmed-dinar" > /etc/schroot/schroot.conf
  - sudo echo "groups=sbuild" > /etc/schroot/schroot.conf
  - sudo echo "root-groups=root" > /etc/schroot/schroot.conf
  - sudo debootstrap --variant=buildd --arch amd64 xenial /JAIL/ http://mirror.math.princeton.edu/pub/ubuntu/
  - sudo mount proc /JAIL/proc -t proc
  - sudo cat /etc/schroot/schroot.conf
  - ls /JAIL
  - sudo touch /JAIL/chroot-setup.sh
  - sudo chmod 777 /JAIL/chroot-setup.sh
  - sudo echo "#!/bin/bash" > /JAIL/chroot-setup.sh
  - sudo echo "gcc --version" > /JAIL/chroot-setup.sh
  - sudo echo "apt-get install default-jdk" > /JAIL/chroot-setup.sh
  - sudo echo "java -version" > /JAIL/chroot-setup.sh
  - sudo echo "exit" > /JAIL/chroot-setup.sh
  - sudo cat /JAIL/chroot-setup.sh
  - sudo chmod +x /JAIL/chroot-setup.sh
install:
  - sudo chroot /JAIL ./chroot-setup.sh
script:
  - sudo echo "done!"
